### PR TITLE
more non-deterministic tests

### PR DESCRIPTION
**Pull request by gregsdennis**
@jg-rp Please let me know if this is what you expect.

### CODE REVIEW

**Comment by gregsdennis** [comment]
rebased after aut0-cts-build merged

**Comment by jg-rp** [comment]
Looks good, @gregsdennis . :+1: 

I note that I did need to build `cts.json` manually when adding the `more-non-determinism` branch as a submodule to JSON P3. Anyone using the `nondeterministic` branch of JSON P3 will need to do the same, for now.

**Comment by gregsdennis** [comment]
We merged a GH Action that should automatically rebuild once this is merged.  (This is the first test of that action.)

**Comment by gregsdennis** [comment]
@jg-rp @Marcono1234 the action worked! 🎉

https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/commit/c6261e15635321c728b2b7ba4a822f73b2698b7a

**Pull request merged**
